#!/bin/bash
FILE=$1
MESSAGE=$(cat $FILE)
TAGS=$(git rev-parse --abbrev-ref HEAD | tr -d "$(git config user.initials)_" | grep -Eo '^(\w+)?(\w+[-_])?[0-9]+([-_](\w+[-_])?[0-9]+)?' | grep -Eo '(\w+[-])?[0-9]+' | tr "[:lower:]" "[:upper:]" | tr "\n" '|' | sed 's/|/ | /g'  )
len=${#TAGS}
TICKET=[${TAGS::len-3}]
if [[ $TICKET == "[]" || "$MESSAGE" == "$TICKET"* ]];then
  exit 0;
fi

echo "$TICKET $MESSAGE" > $FILE
